package com.mg4news.matcha

import java.time.LocalDateTime
import org.mongodb.scala.bson.ObjectId

// Document for users, each user has:
// - a first name
// - a last name
// - an email, used as the unique author identifier in the "Doc" document
object DocUser {
  def apply(firstName: String, lastName: String, email: String): DocUser =
    DocUser(new ObjectId(), firstName, lastName, email)
}
case class DocUser(_id: ObjectId, firstName: String, lastName: String, email: String)

// Document for the actual issued document (recursive much?). An issued document has:
// - a name
// - a description
// - a project, TLA from DocProj
// - a category (because "type" is a keyword!) from DocCat
// - an author, email from DocUser
// - a list of keywords from DocWord
// - an autogenerated creation timestamp
object DocDoc {
  def apply(
             name: String,
             description: String,
             proj: String,
             category: String,
             email: String,
             keywords: String = ","): DocDoc =
    DocDoc(new ObjectId(), name, description, proj, category, email: String, keywords, created=LocalDateTime.now())
}
case class DocDoc(
  _id: ObjectId,
  name: String,
  description: String,
  proj: String,
  category: String,
  email: String,
  keywords: String,
  created: LocalDateTime)




