package org.mg4news.Doccy

import java.time.LocalDateTime
import org.mongodb.scala.bson.ObjectId

// Document for the actual issued document (recursive much?). An issued document has:
// - a name
// - a description
// - a project, TLA from DocProj
// - a category (because "type" is a keyword!) from DocCat
// - an author, email from DocUser
// - a list of keywords from DocWord
// - an autogenerated creation timestamp
object DocDoc {
  def apply(
             name: String,
             description: String,
             proj: String,
             category: String,
             email: String,
             keywords: String = ","): DocDoc =
    DocDoc(new ObjectId(), name, description, proj, category, email: String, keywords, created=LocalDateTime.now())
}
case class DocDoc(
  _id: ObjectId,
  name: String,
  description: String,
  proj: String,
  category: String,
  email: String,
  keywords: String,
  created: LocalDateTime)




